### ISSUE TITLE
Move all spark related methods to a new class SparkUtils

### ISSUE THREAD

**Issue by gengliangwang** [pyspark-ai/pyspark-ai#108]
Create a new class for all the utility method related to Spark, for example, `_get_dataframe_results`, `_get_df_schema`, etc.
The refactoring can simplify the code in `pyspark_ai.py`.

**Comment by SemyonSinchenko** [comment]
I can try to do it. May you assign me to this?

**Comment by gengliangwang** [comment]
@SemyonSinchenko Yes, thank you!
