### ISSUE TITLE
Introduce new example for UDF generation

### ISSUE THREAD

**Issue by gengliangwang** [pyspark-ai/pyspark-ai#111]
We need a more complicated or useful example for UDF Generation in https://github.com/databrickslabs/pyspark-ai/blob/master/examples/example.ipynb

**Comment by SemyonSinchenko** [comment]
Recently I added some tests of end2end UDFs generation. I can add the same cases as examples to `example.ipynb` or create a separate notebook.

**Comment by gengliangwang** [comment]
> Recently I added some tests of end2end UDFs generation. I can add the same cases as examples to example.ipynb or create a separate notebook.

Thanks! The example.ipynb is getting bigger, let's create a UDF.ipynb instead.

**Comment by SemyonSinchenko** [comment]
I'll do it. Please assign this ticket to me.
