### ISSUE TITLE
Add end-to-end test for UDF generation

### ISSUE THREAD

**Issue by gengliangwang** [pyspark-ai/pyspark-ai#112]
Create a UDF via `@spark_ai.udf` annotation, and verify the input and output.

**Comment by SemyonSinchenko** [comment]
Do I understand right that I should just take prompts (from documentation examples at first, like an example for `def previous_years_sales`), wrap them via `@aprk_ai.udf` and create test inputs-outputs [here](https://github.com/pyspark-ai/pyspark-ai/blob/master/tests/test_spark_ai.py#L229)?

**Comment by gengliangwang** [comment]
@SemyonSinchenko thanks for looking into this. 
The code pointer you show is with cache. This issue expectes a real end-to-end test with openai. I am currently setting the OPENAI key as a secret in the github action. I will get back here today when it is done.

**Comment by gengliangwang** [comment]
@SemyonSinchenko I tried hard but I am unable to use the ENV variable `OPENAI_API_KEY`: https://github.com/pyspark-ai/pyspark-ai/pull/139
Could you check other good first issues? I have to stop figuring out the end-to-end tests today.

**Comment by SemyonSinchenko** [comment]
Wait a little. I need anyway to test it by myself locally with my own openai key. I do not think that it will be fast cause I'm totally new with pyspark-ai. And I need to prepare 5-6 test cases at least. So, you can assign me to the ticket and I will prepare everything in few days. And you will be able to setup tests on GHA in this time.

**Comment by gengliangwang** [comment]
Sure, @SemyonSinchenko Thanks a lot!

**Comment by gengliangwang** [comment]
@SemyonSinchenko FYI https://github.com/pyspark-ai/pyspark-ai/pull/139 is merged. The test will only be executed when a commit is pushed to the master branch.
For any end-to-end test PRs, I will verify them on my local before merged. Thanks!
