### ISSUE TITLE
Demo code has error in DBR 13.2

### ISSUE THREAD

**Issue by zhangabner** [pyspark-ai/pyspark-ai#118]
spark = spark_ai._spark
# create a dataframe containing different bike product_catagory and product_count
df = spark.createDataFrame(
    [
        ("children bike", 20),
        ("comfort bike", 15),
        ("mountain bike", 10),
        ("electric bike", 5),
        ("road bike", 3),
        ("cruisers bike", 8)
    ],
    ["product_category", "product_count"]
)
df.ai.transform("pivot using product_category for product_count").show()\

it got error:
INFO:spark_ai:Creating temp view for the transform:
df.createOrReplaceTempView("spark_ai_temp_view_fb06c3")

> Entering new AgentExecutor chain...
OutputParserException: Could not parse LLM output: `SELECT *
FROM spark_ai_temp_view_fb06c3
PIVOT (SUM(product_count) FOR product_category IN ('category1', 'category2', 'category3', ...))`

**Comment by gengliangwang** [comment]
@zhangabner Thanks for reporting. Currently the transform method works best with gpt-4. Are you currently using other LLM model?

**Comment by zhangabner** [comment]
Thanks for replying. I use GPT3.5.  It works on other demos, but not this one.

**Comment by gengliangwang** [comment]
It is expected that GPT 3.5 won't well with dataframe transformation. For other APIs, it may work well. We will put this into docs.
