### ISSUE TITLE
Fix project dependencies

### ISSUE THREAD

**Issue by MrPowers** [pyspark-ai/pyspark-ai#137]
Some project dependencies should be flagged as `dev-dependencies`.  We want the fewest dependencies possible when this project is pip installed.

A quinn user [recently informed me](https://github.com/MrPowers/quinn/issues/124) that dev-dependencies are being deprecated and poetry is moving towards group dependencies.

This should work better for this project too.  We should think about what dependency groups would be ideal for this project.

**Comment by SemyonSinchenko** [comment]
It looks like that ticket was done:
- we have dev-group (install --with=dev)
- we have extras (install --extra=)

Whats else should be done here to resolve it?

**Comment by SemyonSinchenko** [comment]
@gengliangwang It seems to me that this one can be closed as completed.
