### ISSUE TITLE
[Proposal] Add example notebooks as pages to documentation

### ISSUE THREAD

**Issue by SemyonSinchenko** [pyspark-ai/pyspark-ai#142]
It looks like it is possible to add Jupyter notebooks as part of documentation with the following extension: https://pypi.org/project/mkdocs-jupyter/

**Comment by gengliangwang** [comment]
@SemyonSinchenko +1, this is a great idea. We can avoid duplicated code on doc website and example notebooks. Can I assign this one to you?

**Comment by SemyonSinchenko** [comment]
> @SemyonSinchenko +1, this is a great idea. We can avoid duplicated code on doc website and example notebooks. Can I assign this one to you?

Yes, I can try!
