### ISSUE TITLE
Change the return type of `df.ai.verify` from None to bool

### ISSUE THREAD

**Issue by gengliangwang** [pyspark-ai/pyspark-ai#152]
The current signature is `DataFrame.ai.verify(desc: Optional[str] = None, cache: bool = True) -> None`. However, it makes more sense to be
```
DataFrame.ai.verify(desc: Optional[str] = None, cache: bool = True) -> bool
```

**Comment by gengliangwang** [comment]
cc @SemyonSinchenko are you interested on this one?

**Comment by SemyonSinchenko** [comment]
> cc @SemyonSinchenko are you interested on this one?

Yes, I can make a look!
