### ISSUE TITLE
Bug: "cannot import name 'Row' from 'sqlalchemy'" caused by import of old Langchain package version

### ISSUE THREAD

**Issue by Gghaibeh** [pyspark-ai/pyspark-ai#186]
- Bug signature: "cannot import name 'Row' from 'sqlalchemy'" caused by import of old Langchain package version 
- Occurs when importing `pyspark-ai==0.1.19` on a machine that already has `langchain==0.0314` installed

Recreate the environment:
- Prepare a machine with an older version of langchain that is within the  :
  - `pip install langchain==0.0.314`
  
  Recreate the issue:
  - `pip install pyspark-ai==0.1.19`
  - `from langchain.chat_models import ChatOpenAI
     from pyspark_ai import SparkAI
     chatOpenAI = ChatOpenAI(model = 'gpt-3.5-turbo')
    spark_ai = SparkAI(llm = chatOpenAI)
    spark_ai.activate()`

Produces:
"cannot import name 'Row' from 'sqlalchemy' " 

- See https://github.com/langchain-ai/langchain/pull/14488/files

Proposed Fix:
- Modifiying pyspark-ai to `import langchain>=0.0.353` fixes the issue
- Modify [pyproject.toml line 28](https://github.com/pyspark-ai/pyspark-ai/blob/8bd2602cef79a04b13b9c3e5dd19da6b1aa82a0e/pyproject.toml#L28)
 to langchain = ">=0.0.353,<0.1.0"

**Comment by gengliangwang** [comment]
@Gghaibeh Thanks for reporting this issue! Do you mind creating a PR for this? I will review and merge it.

**Comment by Gghaibeh** [comment]
Hey Gengliang   This is an awesome package. Truly !  Will start the PR shortly.  CheersGerardOn Jan 2, 2024, at 10:44 AM, Gengliang Wang ***@***.***> wrote:﻿
@Gghaibeh Thanks for reporting this issue! Do you mind creating a PR for this? I will review and merge it.

**Comment by gengliangwang** [comment]
Merged https://github.com/pyspark-ai/pyspark-ai/pull/187 and release it in v0.1.20.
@Gghaibeh @pkandarpa-cs thanks for the fix!
