### ISSUE TITLE
Am exploring Pyspark AI ValidationError: 1 validation error for PythonExecutor df instance of DataFrame expected (type=type_error.arbitrary_type; expected_arbitrary_type=DataFrame)

### ISSUE THREAD

**Issue by saikumarveera** [pyspark-ai/pyspark-ai#192]
Below is the code which iam running in databricks and its throwing the below error
CODE:-
data = [('Toyota', 1849751, -9), ('Ford', 1767439, -2), ('Chevrolet', 1502389, 6),
        ('Honda', 881201, -33), ('Hyundai', 724265, -2), ('Kia', 693549, -1),
        ('Jeep', 684612, -12), ('Nissan', 682731, -25), ('Subaru', 556581, -5),
        ('Ram Trucks', 545194, -16), ('GMC', 517649, 7), ('Mercedes-Benz', 350949, 7),
        ('BMW', 332388, -1), ('Volkswagen', 301069, -20), ('Mazda', 294908, -11),
        ('Lexus', 258704, -15), ('Dodge', 190793, -12), ('Audi', 186875, -5),
        ('Cadillac', 134726, 14), ('Chrysler', 112713, -2), ('Buick', 103519, -42),
        ('Acura', 102306, -35), ('Volvo', 102038, -16), ('Mitsubishi', 102037, -16),
        ('Lincoln', 83486, -4), ('Porsche', 70065, 0), ('Genesis', 56410, 14),
        ('INFINITI', 46619, -20), ('MINI', 29504, -1), ('Alfa Romeo', 12845, -30),
        ('Maserati', 6413, -10), ('Bentley', 3975, 0), ('Lamborghini', 3134, 3),
        ('Fiat', 915, -61), ('McLaren', 840, -35), ('Rolls-Royce', 460, 7)]

auto_df = spark_ai._spark.createDataFrame(data, ["Brand", "US_Sales_2022", "Sales_Change_Percentage"])
auto_df.ai.plot()

ERROR:-

ValidationError: 1 validation error for PythonExecutor
df
  instance of DataFrame expected (type=type_error.arbitrary_type; expected_arbitrary_type=DataFrame)

**Comment by SemyonSinchenko** [comment]
May you please provide an information about Databricks Runtime version and pyspark-ai version?

**Comment by saikumarveera** [comment]
i just did pip install  pyspark-ai and DBR runtime is 14.3

**Comment by SemyonSinchenko** [comment]
Is it a shared-cluster with Spark Connect? May you please try `spark.hasattr("_jvm")` in the Notebook?

**Comment by saikumarveera** [comment]
Yes its a shared cluster , i can see access mode as shared in my Databricks

**Comment by SemyonSinchenko** [comment]
@gengliangwang It looks like a bug related to `SparkConnect`. May you assign it to me? I will try to check, is it working fine when session is a SparkConnect and what is a returned type. Because it looks mostly as a type-validation error when initializing `PythonExecutor` object (it expects to get `pyspark.sql.DataFrame` but in this case it is possible that `pyspark.sql.connect.DataFrame` is passed). I will run tests later.

**Comment by saikumarveera** [comment]
> Is it a shared-cluster with Spark Connect? May you please try `spark.hasattr("_jvm")` in the Notebook?

checked this as well and its not working in shared cluster

**Comment by saikumarveera** [comment]
> @gengliangwang It looks like a bug related to `SparkConnect`. May you assign it to me? I will try to check, is it working fine when session is a SparkConnect and what is a returned type. Because it looks mostly as a type-validation error when initializing `PythonExecutor` object (it expects to get `pyspark.sql.DataFrame` but in this case it is possible that `pyspark.sql.connect.DataFrame` is passed). I will run tests later.

yes when i see the type it is  pyspark.sql.connect.DataFrame not pyspark.sql.DataFrame
